/*
<!-- BEGIN INVN LICENSE -->
TDK InvenSense 5 Clause License

Copyright (c) 2025, Invensense, Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

4. This software, with or without modification, must only be used with a
TDK InvenSense sensor.

5. Any software provided in binary form under this license, whether embedded
in source code or provided as a compiled library or application, must not
be reverse engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
<!-- END INVN LICENSE -->
*/

/* This file was generated by the invn.pysonic Python package. It may need some
 * manual adjustment to work correctly within your application. In particular,
 * you may need to modify the includes if you have some non-standard include
 * paths or if you're using a version of soniclib before the invn namespace was
 * added.
 *
 * We also assume that the required algorithm header icu_algo_format.h is provided
 * at the include path <invn/soniclib/sensor_fw/icu_gpt>. In the case of
 * an official TDK Invensense release, the plugin support package for the
 * algorithm contains the header at this location.
 *
 * Generated from: measurement_config.json
 *
 * invn.pysonic version: 4.35.1
 */

#include <invn/icu_interface/shasta_external_regs.h>
#include <invn/icu_interface/ch-rangefinder/structs.h>  // algorithm specific definitions
#include <invn/soniclib/soniclib.h>

measurement_queue_t measurement_config_queue = {
    .intconfig=0,
    .meas_start=0,
    .meas_stop=0,
    .current_meas=0,
    .trigsrc=1,
    .reserved=0,
    .meas={
        {
            .trx_inst={
                {
                    .cmd_config=33569,
                    .length=512
                },
                {
                    .cmd_config=14370,
                    .length=128
                },
                {
                    .cmd_config=42,
                    .length=43136
                },
                {
                    .cmd_config=3,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                }
            },
            .meas_period=0,
            .odr=4,
            .meas_flags=0
        },
        {
            .trx_inst={
                {
                    .cmd_config=33569,
                    .length=512
                },
                {
                    .cmd_config=14370,
                    .length=128
                },
                {
                    .cmd_config=42,
                    .length=43136
                },
                {
                    .cmd_config=3,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                },
                {
                    .cmd_config=0,
                    .length=0
                }
            },
            .meas_period=0,
            .odr=4,
            .meas_flags=0
        }
    }
};

InvnAlgoRangeFinderConfig measurement_config_cfg  = {
    .meas_cfg={
        {
            .ringdown_cancel_samples=20,
            .static_target_samples=0,
            .thresholds={
                .stop_index={
                    40,
                    80,
                    120,
                    160,
                    200,
                    240,
                    280,
                    320
                },
                .threshold={
                    3000,
                    1800,
                    1200,
                    900,
                    600,
                    450,
                    200,
                    100
                }
            },
            .num_ranges=1,
            .iq_output_format=0,
            .filter_update_modulo=0,
            .reserved=0
        },
        {
            .ringdown_cancel_samples=20,
            .static_target_samples=0,
            .thresholds={
                .stop_index={
                    40,
                    80,
                    120,
                    160,
                    200,
                    240,
                    280,
                    320
                },
                .threshold={
                    3000,
                    1800,
                    1200,
                    900,
                    600,
                    450,
                    200,
                    100
                }
            },
            .num_ranges=1,
            .iq_output_format=0,
            .filter_update_modulo=0,
            .reserved=0
        }
    }
};

